### ISSUE TITLE
Frontend: "Uncaught ReferenceError: gtag ist not defined" in version 13.0.1

### ISSUE THREAD

**Issue by MKupi** [DirkPersky/typo3-dp_cookieconsent#159]
dp_cookieconsent 13.0.1 is broken if you do not use Google Tag Manager.
Reason is a missing condition in Configuration/TypoScript/setup.typoscript.
In version 13.0.0 there was a condition:
```
[{$plugin.tx_cookieconsent.settings.tracking.googleTagManager.id} != ""]
@import 'EXT:dp_cookieconsent/Configuration/TypoScript/Tracking/googleTagManager.typoscript'
[END]
```
In version 13.0.1 the condition around `@import ... googleTagManager.typoscript` is missing.

**Comment by DirkPersky** [comment]
But that condition will break TYPO3 v12.
Also, the condition seems to be unnecessary because it is already handled in tracking.ts.
The following code already checks the condition:
```
page.headerData.998 {
    20 = COA
    20 {
        if {
            value = {$plugin.tx_cookieconsent.settings.tracking.googleTagManager.id}
        }
    }
}
```

Therefore, there is no reason to add that condition back again.

**Comment by lilu82** [comment]
I have also installed version 13.0.1, TYPO3 12, do not use TagManager and use the Dynamic Ajax Content element. I have integrated setup and constants according to the documentation and now get the following message in the frontend when I confirm the cookie hint and want to display the content. The content remains hidden because this JavaScript error message appears.
Uncaught ReferenceError: gtag is not defined

What am I doing wrong?

**Comment by MKupi** [comment]
@lilu82 as far as I see you do nothing wrong, IMO it's a bug or at least a breaking change that is not documented. So I don't understand why this issue was closed.
The easiest soution is to add
`plugin.tx_cookieconsent.settings.tracking.googleTagManager.id >`
in your TypoScript constants.
