### ISSUE TITLE
log/history of given consent

### ISSUE THREAD

**Issue by r3n3rb** [DirkPersky/typo3-dp_cookieconsent#37]
Do you have plans to record the given consent in the database or in a file?

**Comment by DirkPersky** [comment]
No not at the moment. What thoughts do you play with and what exactly do you want to evaluate?

Just to see who accepts and who doesn't?

**Comment by r3n3rb** [comment]
The data protectionists often specify that there must also be documentation of who gave their consent, so that evidence is available in the event of an action.

More and more consent management tool providers are pointing to this which in turn has an impact on pricing and external costs.

**Comment by darthnorman** [comment]
What do you want to save, tho? IP address that changes every now and then? Names you don't have? That rule is nonsense. The only log there is, is the cookie itself located on the client's machine.

**Comment by criwe** [comment]
Hi all!
I found that (closed) issue, but want to share what I know from other providers. I´ve listen to a webinar of Usercentrics some time ago and I was wondering how they could track the consent. I asked and received the following answer:

"Usercentrics follows the principle of data minimization. UC will only store as much and as many personal data as are necessary for the identification of the user within the scope of the proof of consent. These are the Consent data (time, date of the Consent) and the anonymized IP address. In addition, we use a pseudonymization concept. Only with the help of the user himself and the publication of his Consent ID can an identification take place." (original message was in german)
According to their statement, the recording of the ip address falls under the legitimate interest (GDPR), because it is neccessary to fit the need to prove consent.

@darthnorman as far as i understood the concept of usercentrics, the Consent ID is stored on the user's side, most likely in a cookie. If the user deletes it, identification is of course no longer possible (but also not necessary, because then the user has no more proof that he was tracked.).
But as long as that cookie (and possible other tracking cookies) are present, the identification is possible. Many users will not delete their cookies regularly (sadly).

Of course, the sense of it is still debatable. But maybe the concept gets a bit clearer.
In my opinion it would be a good feature to keep up with other providers.

Best,
Christoph

PS: @DirkPersky please reopen, if you think that would be usefull enhancement (i can´t reopen it)

**Comment by DirkPersky** [comment]
Hmm yeah, but it don't want to save user informations like that.

I have a Germany Data-Protection Part where the storage of data is described.

```
### Cookie-Einwilligung mit DP-Cookie-Consent
Unsere Website nutzt eine open source - Cookie-Consent-Technologie, um Ihre Einwilligung zur Speicherung bestimmter Cookies in Ihrem Browser abzulegen. Der Sourcecode ist über github downloadbar. Wenn Sie unserer Website betreten, wird ein DP-Cookie in Ihrem Browser gespeichert, in dem die von Ihnen erteilten Einwilligungen oder der Widerruf dieser Einwilligungen gespeichert werden. Diese Datenwerden nicht weitergegeben. Die erfassten Daten werden im Browser gespeichert, bis Sie selbst das Cookie löschen oder automatisch durch den Browser löschen lassen. Der Einsatz der Cookie-Consent-Technologie erfolgt, um die gesetzlich vorgeschriebenen Einwilligungen für den Einsatz von Cookies einzuholen. Rechtsgrundlage hierfür ist Art. 6 Abs. 1 S. 1 lit. c DSGVO.
```

Translate it if you want to know how i identify the user ;)

**Comment by criwe** [comment]
Thanks for that!
Best
Christoph
